[package]
edition = "2021"
name = "abi"
version = "0.1.0"

[dependencies]
prost = "0.13.4"
sqlx = { version = "0.8.3", features = ["postgres"] }
thiserror = "2.0.11"
tonic = "0.12.3"

[build-dependencies]
tonic-build = "*"
